configMapGenerator:
  - files:
      - application.yml
    name: 82273952-configmap
resources:
  - ../../base
  - pvc.yaml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
  - name: cepgstapacr.azurecr.io/82273952
    newTag: "202411260237"